//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaglarBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public string CommentIcerik { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<int> Postid { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual Users Users { get; set; }
    }
}
